version: '3.8'

services:    
  neuroforge-frontend:
    build: 
      context: .
      args:
        - VITE_API_HOST=${API_HOST}
        - VITE_CONTROL_HOST=${CONTROL_HOST}
    image: wisrovi/w_darwin_ops-frontend:latest
    ports:
      - "5810:4173"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VITE_API_HOST=${API_HOST}
      - VITE_CONTROL_HOST=${CONTROL_HOST}
    env_file:
      - control_host.env
    networks:
      - train_service

networks:
  train_service:
    name: train_service
    external: true
